USE OPCON

SELECT 
SNAME.SKDNAME AS [SCHEDULE]
,JMASTER_AUX.JOBNAME AS [JOB]
,JMASTER_AUX.JAVALUE AS [JOB VALUE]   
FROM JMASTER_AUX,SNAME   
WHERE JAVALUE like '%<keyword>%'  AND 
JMASTER_AUX.SKDID=SNAME.SKDID