select s.skdname as [SCHEDULE], j.jobname as [JOB]
from sname s
join jmaster j
on s.skdid = j.skdid
left outer join
(
SELECT ENSGROUPS.GROUPNAME AS ENSGROUP, CASE WHEN ENSGROUPS.GROUPTYPE = 'S' THEN 'Schedule' WHEN ENSGROUPS.GROUPTYPE = 'J' THEN 'Job' END AS GROUPTYPE,

        SELECTED.SKDNAME AS SCHEDULE, SELECTED.JOBNAME AS JOB, ENSTRIGGERS.TRIGGERNAME AS [TRIGGER],
        CASE WHEN ENSMESSAGES.ACTIONTYPE = 2 THEN 'EMAIL' END AS [TYPE], CASE WHEN ENSMESSAGES.ACTIONACTIVE = 1 THEN 'True' WHEN ENSMESSAGES.ACTIONACTIVE = 0 THEN 'FALSE' END AS ACTIVE,
        ENSMESSAGES.ACTIONMSG AS MESSAGE

FROM ENSGROUPS
LEFT OUTER JOIN ENSACTIONS ON ENSACTIONS.GROUPOFID = ENSGROUPS.GROUPOFID
LEFT OUTER JOIN ENSMESSAGES ON ENSMESSAGES.ACTIONID = ENSACTIONS.ACTIONID
LEFT OUTER JOIN

(
  SELECT ENSGROUPS.GROUPOFID, SNAME.SKDID, SNAME.SKDNAME, JMASTER.JOBNAME
  FROM SNAME
  INNER JOIN JMASTER ON JMASTER.SKDID = SNAME.SKDID
  LEFT OUTER JOIN ENSSELECTED ON ENSSELECTED.SELECTID = SNAME.SKDID
  LEFT OUTER JOIN ENSGROUPS ON ENSGROUPS.GROUPOFID = ENSSELECTED.GROUPOFID AND ENSGROUPS.GROUPEXCLSEL = 0 AND ENSGROUPS.GROUPTYPE = 'S' /* Schedule Group - Exclude by Default */
  WHERE ENSGROUPS.GROUPOFID IS NOT NULL

  UNION

  SELECT ENSGROUPS.GROUPOFID, SNAME.SKDID, SNAME.SKDNAME, JMASTER.JOBNAME
  FROM SNAME
  INNER JOIN JMASTER ON JMASTER.SKDID = SNAME.SKDID
  INNER JOIN ENSGROUPS ON ENSGROUPS.GROUPEXCLSEL = 1 AND ENSGROUPS.GROUPTYPE = 'S' /* Schedule Group - Include by Default */

  LEFT OUTER JOIN ENSSELECTED ON ENSSELECTED.SELECTID = SNAME.SKDID
  WHERE ENSSELECTED.SELECTID IS NULL

  UNION

  SELECT ENSGROUPS.GROUPOFID, SNAME.SKDID, SNAME.SKDNAME, JMASTER.JOBNAME

  FROM SNAME
  INNER JOIN JMASTER ON JMASTER.SKDID = SNAME.SKDID
  INNER JOIN ENSGROUPS ON ENSGROUPS.GROUPEXCLSEL = 0 AND ENSGROUPS.GROUPTYPE = 'J' /* Job Group - Exclude by Default */
  INNER JOIN ENSSELECTED ON ENSSELECTED.GROUPOFID = ENSGROUPS.GROUPOFID AND ENSSELECTED.SELECTID = SNAME.SKDID AND ENSSELECTED.SELECTSTRING = JMASTER.JOBNAME
  WHERE ENSSELECTED.SELECTID IS NOT NULL

  UNION

  SELECT ENSGROUPS.GROUPOFID, SNAME.SKDID, SNAME.SKDNAME, JMASTER.JOBNAME
  FROM SNAME
  INNER JOIN JMASTER ON JMASTER.SKDID = SNAME.SKDID
  INNER JOIN ENSGROUPS ON ENSGROUPS.GROUPEXCLSEL = 1 AND ENSGROUPS.GROUPTYPE = 'J' /* Job Group - Include by Default */
  LEFT OUTER JOIN ENSSELECTED ON ENSSELECTED.GROUPOFID = ENSGROUPS.GROUPOFID AND ENSSELECTED.SELECTID = SNAME.SKDID AND ENSSELECTED.SELECTSTRING = JMASTER.JOBNAME
  WHERE ENSSELECTED.SELECTID IS NULL
) SELECTED ON SELECTED.GROUPOFID = ENSGROUPS.GROUPOFID
LEFT OUTER JOIN ENSTRIGGERS ON ENSTRIGGERS.TRIGGERCODE = ENSACTIONS.STATUSCODE AND ENSTRIGGERS.TRIGGERCODE LIKE 'J%'
WHERE ENSGROUPS.GROUPTYPE IN ('J', 'S')
--ORDER BY GROUPTYPE DESC, ENSGROUP, [TRIGGER], SCHEDULE, JOB, TYPE

) a
on s.skdname = a.schedule and j.jobname = a.job and a.[trigger] = 'Job Failed' and a.active = 'True' and a.message is not null
where a.message is null
ORDER BY s.skdname